"""baseline: tasks, agent_runs, agent_run_steps, conversation_states

Represents the complete schema as of app/db_models.py at the time
Alembic was introduced - not autogenerated blindly: every table,
column, index, foreign key, and unique constraint below was verified
against a throwaway temp-file SQLite database bootstrapped via
Base.metadata.create_all() and inspected via sqlite_master (never
against tasks.db), so the DDL here is byte-for-byte equivalent to what
the ORM models already produce. tests/test_alembic_migrations.py
::test_baseline_matches_current_orm_metadata re-verifies this
automatically (via Alembic's own autogenerate diff) so a future model
change without a matching new revision is caught immediately, rather
than silently drifting.

Notable details preserved deliberately, not incidentally:
- agent_runs.run_id has unique=True AND index=True in the ORM model,
  which SQLAlchemy collapses into a single UNIQUE index
  (ix_agent_runs_run_id), not a separate unique constraint plus a
  separate plain index - confirmed from the actual generated DDL.
- agent_run_steps.run_id's foreign key to agent_runs.run_id has no
  ON DELETE clause: the model's cascade="all, delete-orphan" is
  ORM-level only (Python-side DELETE statements issued by SQLAlchemy
  when an AgentRun object is deleted), never a database-level cascade -
  SQLite doesn't even enforce foreign keys by default here, since
  app/database.py never sets PRAGMA foreign_keys=ON. The FK constraint
  itself is still declared, matching the model.
- conversation_states has no foreign keys at all: user_id and
  conversation_id are plain columns (there is no "users" table
  anywhere in this application - user_id is a string tied to
  app.config.API_KEYS, not a database relation).

Revision ID: 0001_baseline
Revises:
Create Date: 2026-07-20

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0001_baseline"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        "tasks",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("done", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_tasks_user_id"), "tasks", ["user_id"], unique=False)

    op.create_table(
        "agent_runs",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("conversation_id", sa.Uuid(), nullable=False),
        sa.Column("message", sa.String(), nullable=False),
        sa.Column("decision_provider", sa.String(), nullable=False),
        sa.Column("is_multi_step", sa.Boolean(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("selected_tool", sa.String(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("duration_ms", sa.Integer(), nullable=False),
        sa.Column("error", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_agent_runs_user_id"), "agent_runs", ["user_id"], unique=False)
    # unique=True here (not a separate UniqueConstraint) - see module docstring.
    op.create_index(op.f("ix_agent_runs_run_id"), "agent_runs", ["run_id"], unique=True)
    op.create_index(op.f("ix_agent_runs_conversation_id"), "agent_runs", ["conversation_id"], unique=False)

    op.create_table(
        "agent_run_steps",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("step_number", sa.Integer(), nullable=False),
        sa.Column("tool", sa.String(), nullable=False),
        sa.Column("arguments_json", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("duration_ms", sa.Integer(), nullable=False),
        sa.Column("error", sa.String(), nullable=True),
        sa.Column("result_summary", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(["run_id"], ["agent_runs.run_id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_agent_run_steps_run_id"), "agent_run_steps", ["run_id"], unique=False)

    op.create_table(
        "conversation_states",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("conversation_id", sa.Uuid(), nullable=False),
        sa.Column("clarification_tool", sa.String(), nullable=True),
        sa.Column("clarification_arguments_json", sa.String(), nullable=True),
        sa.Column("clarification_reason", sa.String(), nullable=True),
        sa.Column("clarification_missing_json", sa.String(), nullable=True),
        sa.Column("clarification_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("confirmation_tool", sa.String(), nullable=True),
        sa.Column("confirmation_arguments_json", sa.String(), nullable=True),
        sa.Column("confirmation_reason", sa.String(), nullable=True),
        sa.Column("confirmation_question", sa.String(), nullable=True),
        sa.Column("confirmation_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_task_id", sa.Integer(), nullable=True),
        sa.Column("context_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "conversation_id", name="uq_conversation_states_user_conversation"),
    )
    op.create_index(op.f("ix_conversation_states_user_id"), "conversation_states", ["user_id"], unique=False)
    op.create_index(
        op.f("ix_conversation_states_conversation_id"), "conversation_states", ["conversation_id"], unique=False
    )


def downgrade() -> None:
    # Deliberately blocked: there is no revision below this one, so
    # "downgrading" it could only ever mean dropping every table and
    # destroying all data. That must never be one `alembic downgrade`
    # away. The correct rollback path for this revision is restoring a
    # pre-migration backup - see README.md's "Database migrations
    # (Alembic)" section.
    raise RuntimeError(
        "Downgrading past the baseline revision would drop every table and "
        "destroy all data - this is intentionally not supported. Restore "
        "from a backup taken before upgrading instead."
    )
